/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 helmet.gltf --transform 
Files: helmet.gltf [11.64MB] > helmet-transformed.glb [805.8KB] (93%)
Author: bluoppVR (https://sketchfab.com/bluoppVR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-helmet-7b095c71ce844118bf5fc9af2f3accd0
Title: Space Helmet
*/

import React, { useState, useEffect } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const [scale, setScale] = useState([0.5, 0.5, 0.5]);

  useEffect(() => {
    const savedScale = localStorage.getItem("modelScale");
    if (savedScale) {
      setScale(JSON.parse(savedScale));
    }
  }, []);

  useEffect(() => {
    localStorage.setItem("modelScale", JSON.stringify(scale));
  }, [scale]);

  const { nodes, materials } = useGLTF("/helmet-transformed.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Material_MR}
        rotation={[Math.PI / 2, 0, 0]}
        scale={scale}
      />
    </group>
  );
}

useGLTF.preload("/helmet-transformed.glb");


